(define (average listOfNumbers)
    (if (null? listOfNumbers)
        (quote List_is_Empty)
        (/ (sum listOfNumbers) (length listOfNumbers))
    )
)
(define (length listOfNumbers)
    (if (null? listOfNumbers)
        0
        (+ 1 (length (cdr listOfNumbers)))
        )
    )
(define (sum listOfNumbers)
    (if (null? listOfNumbers)
        0
        (+ (car listOfNumbers) (sum (cdr listOfNumbers )))
        )
    )
(define a (list 1 2 3 4 5 6))
(display (average a))